/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package notepad;

import formato.Fuente;
import java.awt.Font;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.event.UndoableEditEvent;
import javax.swing.event.UndoableEditListener;
import javax.swing.undo.CannotRedoException;
import javax.swing.undo.*;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;


public class Principal extends javax.swing.JFrame {

int cont = 0;
public static String caja1;
public static int caja2;
public static String caja3;
UndoManager undo=new UndoManager(); 

    
    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        this.barra.setVisible(false);
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        barra = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        deshacer = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        cortar = new javax.swing.JMenuItem();
        copiar = new javax.swing.JMenuItem();
        pegar = new javax.swing.JMenuItem();
        eliminar = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        buscar = new javax.swing.JMenuItem();
        buscar_siguiente = new javax.swing.JMenuItem();
        reemplazar = new javax.swing.JMenuItem();
        ir_a = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        seleccionar_todo = new javax.swing.JMenuItem();
        hora_fecha = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        FormatoAjustesLinea_ = new javax.swing.JCheckBoxMenuItem();
        FormatoFuente_ = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextArea1KeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTextArea1);

        barra.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu5.setText("Edición");
        jMenu5.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jMenu5MenuSelected(evt);
            }
        });

        deshacer.setText("Deshacer");
        deshacer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deshacerActionPerformed(evt);
            }
        });
        deshacer.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                deshacerKeyPressed(evt);
            }
        });
        jMenu5.add(deshacer);
        jMenu5.add(jSeparator1);

        cortar.setText("Cortar");
        cortar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cortarActionPerformed(evt);
            }
        });
        jMenu5.add(cortar);

        copiar.setText("Copiar");
        copiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                copiarActionPerformed(evt);
            }
        });
        jMenu5.add(copiar);

        pegar.setText("Pegar");
        pegar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pegarActionPerformed(evt);
            }
        });
        jMenu5.add(pegar);

        eliminar.setText("Eliminar");
        eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActionPerformed(evt);
            }
        });
        jMenu5.add(eliminar);
        jMenu5.add(jSeparator2);

        buscar.setText("Buscar...");
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });
        jMenu5.add(buscar);

        buscar_siguiente.setText("Buscar siguiente");
        buscar_siguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscar_siguienteActionPerformed(evt);
            }
        });
        jMenu5.add(buscar_siguiente);

        reemplazar.setText("Reemplazar");
        reemplazar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reemplazarActionPerformed(evt);
            }
        });
        jMenu5.add(reemplazar);

        ir_a.setText("Ir a...");
        jMenu5.add(ir_a);
        jMenu5.add(jSeparator3);

        seleccionar_todo.setText("Seleccionar todo");
        seleccionar_todo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seleccionar_todoActionPerformed(evt);
            }
        });
        jMenu5.add(seleccionar_todo);

        hora_fecha.setText("Hora y fecha");
        hora_fecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hora_fechaActionPerformed(evt);
            }
        });
        jMenu5.add(hora_fecha);

        jMenuBar1.add(jMenu5);

        jMenu3.setText("Formato");

        FormatoAjustesLinea_.setText("Ajustes de Línea");
        FormatoAjustesLinea_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FormatoAjustesLinea_ActionPerformed(evt);
            }
        });
        jMenu3.add(FormatoAjustesLinea_);

        FormatoFuente_.setText("Fuente...");
        FormatoFuente_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FormatoFuente_ActionPerformed(evt);
            }
        });
        jMenu3.add(FormatoFuente_);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Ver");

        jCheckBoxMenuItem1.setText("Barra de estado");
        jCheckBoxMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItem1ActionPerformed(evt);
            }
        });
        jMenu4.add(jCheckBoxMenuItem1);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addComponent(barra, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(barra, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 13, Short.MAX_VALUE))
        );

        barra.getAccessibleContext().setAccessibleName("barra");

        pack();
    }// </editor-fold>                        
     
    int num = 0;
    private void FormatoAjustesLinea_ActionPerformed(java.awt.event.ActionEvent evt) {                                                     
        switch(num){
            case 0: {
                jTextArea1.setLineWrap(true); 
                num = 1;
                break;
            }
            case 1: {
                jTextArea1.setLineWrap(false);
                num = 0;
                break;
            }
        }

    }                                                    

    private void FormatoFuente_ActionPerformed(java.awt.event.ActionEvent evt) {                                               
        Fuente dialog = new Fuente(new javax.swing.JFrame(), true);
        dialog.setVisible(true);

        if((caja1 == null) && (caja3 == null)){
            
        }
        else{
            int tamaño = Integer.parseInt(caja3);
            Font font = new Font(caja1, caja2, tamaño);
            jTextArea1.setFont(font);
        }

    }                                              
     
     
    private void jCheckBoxMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {                                                   
      cont++;
        if (cont == 1) {
            barra.setVisible(true);
        } else if (cont == 2) {
            barra.setVisible(false);
            cont = 0;
        }
        
         
    }                                                  
        int Fila=0, columna=0, pos=0;  
        
    private void jTextArea1KeyPressed(java.awt.event.KeyEvent evt) {                                      
     
    try {
        pos = jTextArea1.getCaretPosition();
        Fila= jTextArea1.getLineOfOffset(pos);
        columna=pos-jTextArea1.getLineStartOffset(Fila);
        }
    catch(Exception excp)
            {
                
            }
    if (jTextArea1.getText().length()==0){Fila=0; columna=0;}
    
    barra.setText("Fila " +(Fila+1)+",Columna "+(columna+1));
    
   
    
     
     
    }                                     

    private void deshacerActionPerformed(java.awt.event.ActionEvent evt) {                                         

        try{
            undo.undo();
        }catch(CannotUndoException ex){
            ex.printStackTrace();
        }

    }                                        

    private void deshacerKeyPressed(java.awt.event.KeyEvent evt) {                                    

    }                                   

    private void cortarActionPerformed(java.awt.event.ActionEvent evt) {                                       

        jTextArea1.cut();
    }                                      

    private void copiarActionPerformed(java.awt.event.ActionEvent evt) {                                       
        jTextArea1.copy();
    }                                      

    private void pegarActionPerformed(java.awt.event.ActionEvent evt) {                                      

        jTextArea1.paste();
    }                                     

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {                                         

        String area=jTextArea1.getText();

        if(area.isEmpty()==false){

            jTextArea1.setText("");
        }

    }                                        

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {                                       

        String msj;
        try{

            msj = JOptionPane.showInputDialog("Buscar");
            while(!jTextArea1.getText().contains(msj)){
                JOptionPane.showMessageDialog(null,"No Se Encontró : " +msj+"" ,"Block de notas",JOptionPane.WARNING_MESSAGE );
                msj = JOptionPane.showInputDialog("Buscar");
            }
            jTextArea1.select(jTextArea1.getText().indexOf(msj),
                jTextArea1.getText().indexOf(msj) + msj.length());
        }
        catch(Exception ex){

        }

    }                                      

    private void buscar_siguienteActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        String Msj="";

        try{
            jTextArea1.select(jTextArea1.getText().indexOf(Msj,jTextArea1.getText().indexOf(Msj)+1),
                jTextArea1.getText().indexOf(Msj,jTextArea1.getText().indexOf(Msj)+1));
        }
        catch (Exception ex){
            JOptionPane.showMessageDialog(null, "Error" + ex.getMessage());

        }

    }                                                

    private void reemplazarActionPerformed(java.awt.event.ActionEvent evt) {                                           

        Reemplazar ver=new Reemplazar(this,true);
        ver.setVisible(true);
    }                                          

    private void seleccionar_todoActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        jTextArea1.requestFocus();
        jTextArea1.selectAll();

        eliminar.setEnabled(true);
        cortar.setEnabled(true);
        copiar.setEnabled(true);

        seleccionar_todo.setEnabled(false);

    }                                                

    private void hora_fechaActionPerformed(java.awt.event.ActionEvent evt) {                                           

        Date dato=new Date();
        DateFormat hora_fecha=new SimpleDateFormat("HH:mm  dd-MM-yyyy");
        jTextArea1.setText(hora_fecha.format(dato));
    }                                          

    private void jMenu5MenuSelected(javax.swing.event.MenuEvent evt) {                                    

    }                                   

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JCheckBoxMenuItem FormatoAjustesLinea_;
    private javax.swing.JMenuItem FormatoFuente_;
    private javax.swing.JLabel barra;
    private javax.swing.JMenuItem buscar;
    private javax.swing.JMenuItem buscar_siguiente;
    private javax.swing.JMenuItem copiar;
    private javax.swing.JMenuItem cortar;
    private javax.swing.JMenuItem deshacer;
    private javax.swing.JMenuItem eliminar;
    private javax.swing.JMenuItem hora_fecha;
    private javax.swing.JMenuItem ir_a;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    public javax.swing.JTextArea jTextArea1;
    private javax.swing.JMenuItem pegar;
    private javax.swing.JMenuItem reemplazar;
    private javax.swing.JMenuItem seleccionar_todo;
    // End of variables declaration                   
}
